env                = "dev"
region             = "ap-south-1"
vpc_cidr           = "10.0.0.0/16"
azs                = ["ap-south-1a", "ap-south-1b"]
ami_id             = "ami-0f918f7e67a3323f0"
instance_type      = "t3.micro"
ssh_cidr_blocks    = []
log_retention_days = 14
cpu_high_threshold = 80
create_sns         = false
alert_email        = ""